[package]
name = "wercker_build_status"
version = "0.1.0"
authors = ["Martin Becker <mbeckerwork@gmail.com>"]

[dependencies]
config = "0.8"
curl = "0.4.11"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0"
colored = "1.6.0"
